import './App.css';
import QRCode from 'react-qr-code';
import { useState } from 'react';


function App() {
  const [text, setText] = useState('');

  function test(e){
    setText(e.target.value);
  }
  return (
    <div className="App">
      <h1>Generate QR Code</h1>
      <QRCode value={text} /><br/>
      <input value={text} onChange={(e) => {test(e)}}/>
      <button onClick={test}>Generate</button>
      <div>
        <p>This QRCode Generated by Zainab &hearts; Developer.</p>
      </div>
    </div>
  );
}

export default App;
